industrie_dict = {0: 'Ingénieur en nanotechnologies',
 1: 'Responsable de la veille scientifique et technique',
 2: 'Responsable de partenariats de recherche',
 3: 'Responsable de projet r&d',
 4: 'Responsable de département r&d',
 5: "Responsable d'équipe de recherche",
 6: 'Responsable éthique, déontologie, conformité',
 7: 'Responsable de la documentation scientifique',
 8: 'Rédacteur médical',
 9: 'Directeur médical',
 10: 'Attaché de recherche clinique (arc)',
 11: 'Attaché de recherche clinique manager',
 12: "Chef de projet ou chef d'études cliniques",
 13: 'Pharmacien développement analytique',
 14: 'Data management/ biostatisticien',
 15: 'Responsable formulation / galénique',
 16: 'Pharmacien en conditionnement clinique',
 17: 'Pharmacien responsable de la transposition industrielle',
 18: 'Enseignement-chercheur',
 19: 'Responsable information médicale',
 20: 'Directeur régional de formation de visiteurs médicaux',
 21: 'Responsable information pharmaceutique',
 22: 'Responsable des relations hospitalières',
 23: 'Délégué hospitalier',
 24: 'Pharmacien conseil',
 25: 'Pharmacien affaires économiques',
 26: "Chargé d'épidémio-économie",
 27: 'Résponsable efficacité commerciale',
 28: "Responsable d'accès au marché",
 29: 'Directeur des opérations',
 30: 'Responsable des études marketing',
 31: 'Pharmacien attaché commercial',
 32: 'Chef de produit sénior',
 33: 'Responsable réseaux prestataires externes',
 34: 'Auditeur /assurance qualité',
 35: 'Responsable contrôle qualité',
 36: 'Coordinateur assurance qualité change control',
 37: 'Pharmacien responsable validation/qualification',
 38: 'Pharmacien libérateur des lots',
 39: "Pharmacien responsable d'un secteur de fabrication",
 40: 'Pharmacien responsable de production',
 41: 'Pharmacien affaires réglementaires',
 42: 'Assistant affaires réglementaires',
 43: 'Responsable de pharmacovigilance',
 44: 'Pharmacien consultant en recrutement',
 45: "Directeur d'établissement"}

phbmr_dict = {0: "Pharmacien directeur de laboratoire d'analyses bio-médicales de biologie médicale",
 1: 'Toxicologie médico-légale',
 2: 'Police scientique',
 3: 'Enseignement-chercheur'}

autres_dict = {0: 'Pharmacien assurance maladie',
 1: 'Pharmacien inspecteur de santé publique',
 2: 'Pharmacien sapeur-pompier',
 3: 'Pharmacien gérant adjoint',
 4: 'Pharmacien de groupement',
 5: 'Pharmacien chef départemental',
 6: 'Pharmacien militaire',
 7: "Pharmacien d'un projet humanitaire"}