industrie = {'Adaptabilité géographique': 22,
    'Adaptabilité à une situation': 21,
    'Administratif': 42,
    'Affaire réglementaire': 43,
    'Analytique': 1,
    'Assurance qualité': 44,
    'Attentioné(e)': 2,
    'Autonome': 23,
    'Bilingue (anglais) ou plus': 24,
    'Biotechnologie': 45,
    'Bon relationnel': 25,
    'Business marketing': 46,
    'Capacité à apprendre rapidement': 3,
    'Carrière militaire ou sapeur pompier': 47,
    'Charismatique': 4,
    'Conformité': 48,
    'Conseils': 49,
    'Convaincant': 26,
    'Coordination': 50,
    'Curiosité': 5,
    'Developpement': 53,
    'Diplomate': 27,
    'Direction': 54,
    'Dispositif médicaux': 55,
    'Documentation scientifique': 56,
    'Droit de la santé': 57,
    'Dynamique': 6,
    'Déontologie': 51,
    'Déplacement géographique': 52,
    'Esprit critique': 7,
    'Esprit scientifique': 8,
    'Esprit synthétique': 9,
    'Essais cliniques': 60,
    'Excellent relationnel': 28,
    'Flexible': 10,
    'Force de proposition': 29,
    'Formulation': 62,
    'Humanitaire': 63,
    'Ingénierie': 64,
    'Inspiré(e)': 11,
    'Inventif(ve)': 12,
    'Leader': 30,
    'Marketing access': 65,
    'Maîtrise outils informatiques': 31,
    'Motivateur': 13,
    'Nanotechnologie': 66,
    'Observateur(rice)': 14,
    'Organisé': 32,
    'Parteneriat': 67,
    'Persuasif(ve)': 15,
    'Pharmacotechnie': 68,
    'Pharmacovigilance': 69,
    'Planificateur': 16,
    'Pluridisciplinarité': 33,
    'Polyvalent': 34,
    'Proactif': 36,
    'Production': 70,
    'Prévoyant': 35,
    'Qualité': 71,
    'Qualité rédactionnelle': 17,
    'Recherche': 72,
    'Relations avec une clientèle': 74,
    'Relations pluridisciplinaire': 75,
    "Ressent la psychologie de l'autre": 18,
    'Rigoureux(se)': 19,
    'Règlementaire': 73,
    'Réactif': 37,
    'Répartition': 76,
    'Santé publique': 77,
    'Sens du challenge': 38,
    'Sociable': 20,
    'Statistique': 78,
    'Stratégique': 39,
    "Travail d'équipe": 40,
    'Veillle scientifique': 79,
    'Vigilant': 41,
    "À l'écoute": 0,
    'Économie/finance': 58,
    'Épidémiologie': 59,
    'Éthique': 61
}

phbmr = {'Adaptabilité géographique': 22,
 'Adaptabilité à une situation': 21,
 'Administratif': 42,
 'Affaire réglementaire': 43,
 'Analytique': 1,
 'Assurance qualité': 44,
 'Attentioné(e)': 2,
 'Autonome': 23,
 'Bilingue (anglais) ou plus': 24,
 'Biotechnologie': 45,
 'Bon relationnel': 25,
 'Business marketing': 46,
 'Capacité à apprendre rapidement': 3,
 'Carrière militaire ou sapeur pompier': 47,
 'Charismatique': 4,
 'Conformité': 48,
 'Conseils': 49,
 'Convaincant': 26,
 'Coordination': 50,
 'Curiosité': 5,
 'Developpement': 53,
 'Diplomate': 27,
 'Direction': 54,
 'Dispositif médicaux': 55,
 'Documentation scientifique': 56,
 'Droit de la santé': 57,
 'Dynamique': 6,
 'Déontologie': 51,
 'Déplacement géographique': 52,
 'Esprit critique': 7,
 'Esprit scientifique': 8,
 'Esprit synthétique': 9,
 'Essais cliniques': 60,
 'Excellent relationnel': 28,
 'Flexible': 10,
 'Force de proposition': 29,
 'Formulation': 62,
 'Humanitaire': 63,
 'Hôpital': 85,
 'Ingénierie': 64,
 'Inspiré(e)': 11,
 'Inventif(ve)': 12,
 "Laboratoire d'analyses": 65,
 'Leader': 30,
 'Marketing access': 66,
 'Maîtrise outils informatiques': 31,
 'Motivateur': 13,
 'Médico-légale': 67,
 'Nanotechnologie': 68,
 'Observateur(rice)': 14,
 'Organisé': 32,
 'Parteneriat': 69,
 'Persuasif(ve)': 15,
 'Pharmacotechnie': 70,
 'Pharmacovigilance': 71,
 'Planificateur': 16,
 'Pluridisciplinarité': 33,
 'Police scientifique': 72,
 'Polyvalent': 34,
 'Proactif': 36,
 'Production': 73,
 'Prévoyant': 35,
 'Qualité': 74,
 'Qualité rédactionnelle': 17,
 'Recherche': 75,
 'Relations avec une clientèle': 77,
 'Relations pluridisciplinaire': 78,
 "Ressent la psychologie de l'autre": 18,
 'Rigoureux(se)': 19,
 'Règlementaire': 76,
 'Réactif': 37,
 'Répartition': 79,
 'Santé publique': 80,
 'Sens du challenge': 38,
 'Sociable': 20,
 'Statistique': 81,
 'Stratégique': 39,
 'Toxicologie': 82,
 "Travail d'équipe": 40,
 'Veillle scientifique': 83,
 'Vigilant': 41,
 "Volonté d'enseigner": 84,
 "À l'écoute": 0,
 'Économie/finance': 58,
 'Épidémiologie': 59,
 'Éthique': 61}

autres = {'Adaptabilité géographique': 22,
 'Adaptabilité à une situation': 21,
 'Administratif': 42,
 'Affaire réglementaire': 43,
 'Analytique': 1,
 'Armée': 44,
 'Assurance': 45,
 'Assurance qualité': 46,
 'Attentioné(e)': 2,
 'Autonome': 23,
 'Bilingue (anglais) ou plus': 24,
 'Biotechnologie': 47,
 'Bon relationnel': 25,
 'Business marketing': 48,
 'Capacité à apprendre rapidement': 3,
 'Carrière militaire ou sapeur pompier': 49,
 'Charismatique': 4,
 'Conformité': 50,
 'Conseils': 51,
 'Convaincant': 26,
 'Coordination': 52,
 'Curiosité': 5,
 'Developpement': 55,
 'Diplomate': 27,
 'Direction': 56,
 'Dispositif médicaux': 57,
 'Documentation scientifique': 58,
 'Droit de la santé': 59,
 'Dynamique': 6,
 'Déontologie': 53,
 'Déplacement géographique': 54,
 'Esprit critique': 7,
 'Esprit scientifique': 8,
 'Esprit synthétique': 9,
 'Essais cliniques': 63,
 'Excellent relationnel': 28,
 'Flexible': 10,
 'Force de proposition': 29,
 'Former': 65,
 'Formulation': 66,
 'Humanitaire': 67,
 'Hôpital': 95,
 'Ingénierie': 68,
 'Inspection': 69,
 'Inspiré(e)': 11,
 'Inventif(ve)': 12,
 "Laboratoire d'analyse": 70,
 'Leader': 30,
 'Marketing access': 71,
 'Maîtrise outils informatiques': 31,
 'Motivateur': 13,
 'Médico-légale': 72,
 'Nanotechnologie': 73,
 'Observateur(rice)': 14,
 'Organisé': 32,
 'Parteneriat': 74,
 'Persuasif(ve)': 15,
 'Pharmacotechnie': 75,
 'Pharmacovigilance': 76,
 'Planificateur': 16,
 'Pluridisciplinarité': 33,
 'Police scientifique': 77,
 'Polyvalent': 34,
 'Proactif': 36,
 'Production': 79,
 'Prévention': 78,
 'Prévoyant': 35,
 'Qualité': 80,
 'Qualité rédactionnelle': 17,
 'Recherche': 81,
 'Relation publique': 83,
 'Relations avec une clientèle': 84,
 'Relations pluridisciplinaire': 85,
 "Ressent la psychologie de l'autre": 18,
 'Rigoureux(se)': 19,
 'Règlementaire': 82,
 'Réactif': 37,
 'Répartition': 86,
 'Santé publique': 87,
 'Sapeur-pompier': 88,
 'Secourisme': 89,
 'Sens du challenge': 38,
 'Sociable': 20,
 'Statistique': 90,
 'Stratégique': 39,
 'Toxicologie': 91,
 "Travail d'équipe": 40,
 'Veillle scientifique': 92,
 'Vigilance': 93,
 'Vigilant': 41,
 "Volonté d'enseigner": 94,
 "À l'écoute": 0,
 'Économie/finance': 60,
 'Éducation': 61,
 'Épidémiologie': 62,
 'Éthique': 64}
    